"""Add imagem_url to cars

Revision ID: 0cabd45c3338
Revises: xxxx_add_rents_table
Create Date: 2025-08-19 12:17:11.859777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cabd45c3338'
down_revision: Union[str, Sequence[str], None] = 'xxxx_add_rents_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_images', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('cars', sa.Column('imagem_url', sa.String(), nullable=True))
    op.alter_column('cars', 'dono_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'dono_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cars', 'imagem_url')
    op.alter_column('car_images', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
